### PR TITLE
Add varz for unconfigured port faucet event

### PR DESCRIPTION
**Pull request by didovesei**

### CODE REVIEW

**Review by anurag6 — APPROVED** [review]

**Comment by anurag6** [comment]
I am curious why the change resulted in a diff in the change counts.

**Comment by didovesei** [comment]
> I am curious why the change resulted in a diff in the change counts.

I guess that's because the Exception:
```
 File "/home/runner/work/forch/forch/forch/forchestrator.py", line 379, in _process_device_placement
    LOGGER.info(
Message: 'Ignored vlan expiration for device %s with expired vlan %d'
```
It is fixed in another PR.

**Comment by grafnu** [comment]
> > I am curious why the change resulted in a diff in the change counts.
> 
> I guess that's because the Exception:
> 
> ```
>  File "/home/runner/work/forch/forch/forch/forchestrator.py", line 379, in _process_device_placement
>     LOGGER.info(
> Message: 'Ignored vlan expiration for device %s with expired vlan %d'
> ```
> 
> It is fixed in another PR.

But the tests here are failing?

**Comment by didovesei** [comment]
> > > I am curious why the change resulted in a diff in the change counts.
> > 
> > 
> > I guess that's because the Exception:
> > ```
> >  File "/home/runner/work/forch/forch/forch/forchestrator.py", line 379, in _process_device_placement
> >     LOGGER.info(
> > Message: 'Ignored vlan expiration for device %s with expired vlan %d'
> > ```
> > 
> > 
> > It is fixed in another PR.
> 
> But the tests here are failing?

I mean it was in another PR which is not merged that... I was going to merge it but got conflict. I will fix it also in this PR.

**Pull request merged**
